### PR TITLE
created a migrations table for log_entry

### PR DESCRIPTION
**Pull request by alesslongaretti**
# Description

Created a schema table for log_entry and included all necessary fields. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

## How Has This Been Tested?

- [x] Using knex migrate:latest command

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by alesslongaretti** [comment]
[Migration - Log_Entry](https://trello.com/c/mcMspKEl/134-migration-logentry)

**Comment by alesslongaretti** [comment]
[Migration - Log_Entry](https://trello.com/c/mcMspKEl/134-migration-logentry)

**Review by dave-vazquez — APPROVED** [review]
This looks good! 🎉

**Review by Afrodo1 — COMMENTED** [review]
Good job Looks great!!

**Pull request merged**
